/* SPDX-License-Identifier: Apache-2.0 */

/****************************************************************************
 * arch/arm/src/pic32czca90/hardware/sam_osc32kctrl.h
 *
 * PIC32CZ CA90 32K Oscillator Control Register Definitions
 *
 ****************************************************************************/

#ifndef __ARCH_ARM_SRC_PIC32CZCA90_HARDWARE_SAM_OSC32KCTRL_H
#define __ARCH_ARM_SRC_PIC32CZCA90_HARDWARE_SAM_OSC32KCTRL_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include "hardware/sam_memorymap.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Register offsets */

#define SAM_OSC32KCTRL_INTENCLR_OFFSET    0x0000
#define SAM_OSC32KCTRL_INTENSET_OFFSET    0x0004
#define SAM_OSC32KCTRL_INTFLAG_OFFSET     0x0008
#define SAM_OSC32KCTRL_STATUS_OFFSET      0x000c
#define SAM_OSC32KCTRL_RTCCTRL_OFFSET     0x0010
#define SAM_OSC32KCTRL_XOSC32K_OFFSET     0x0014
#define SAM_OSC32KCTRL_CFDCTRL_OFFSET     0x0016
#define SAM_OSC32KCTRL_EVCTRL_OFFSET      0x0017
#define SAM_OSC32KCTRL_OSCULP32K_OFFSET   0x001c

/* Register addresses */

#define SAM_OSC32KCTRL_INTENCLR   (SAM_OSC32KCTRL_BASE + SAM_OSC32KCTRL_INTENCLR_OFFSET)
#define SAM_OSC32KCTRL_INTENSET   (SAM_OSC32KCTRL_BASE + SAM_OSC32KCTRL_INTENSET_OFFSET)
#define SAM_OSC32KCTRL_INTFLAG    (SAM_OSC32KCTRL_BASE + SAM_OSC32KCTRL_INTFLAG_OFFSET)
#define SAM_OSC32KCTRL_STATUS     (SAM_OSC32KCTRL_BASE + SAM_OSC32KCTRL_STATUS_OFFSET)
#define SAM_OSC32KCTRL_RTCCTRL    (SAM_OSC32KCTRL_BASE + SAM_OSC32KCTRL_RTCCTRL_OFFSET)
#define SAM_OSC32KCTRL_XOSC32K    (SAM_OSC32KCTRL_BASE + SAM_OSC32KCTRL_XOSC32K_OFFSET)
#define SAM_OSC32KCTRL_CFDCTRL    (SAM_OSC32KCTRL_BASE + SAM_OSC32KCTRL_CFDCTRL_OFFSET)
#define SAM_OSC32KCTRL_EVCTRL     (SAM_OSC32KCTRL_BASE + SAM_OSC32KCTRL_EVCTRL_OFFSET)
#define SAM_OSC32KCTRL_OSCULP32K  (SAM_OSC32KCTRL_BASE + SAM_OSC32KCTRL_OSCULP32K_OFFSET)

/* XOSC32K register bits */

#define OSC32KCTRL_XOSC32K_ENABLE   (1 << 1)
#define OSC32KCTRL_XOSC32K_XTALEN   (1 << 2)
#define OSC32KCTRL_XOSC32K_EN32K    (1 << 3)
#define OSC32KCTRL_XOSC32K_EN1K     (1 << 4)
#define OSC32KCTRL_XOSC32K_RUNSTDBY (1 << 6)
#define OSC32KCTRL_XOSC32K_ONDEMAND (1 << 7)
#define OSC32KCTRL_XOSC32K_STARTUP_SHIFT 8
#define OSC32KCTRL_XOSC32K_STARTUP_MASK  (0x7 << OSC32KCTRL_XOSC32K_STARTUP_SHIFT)
#define OSC32KCTRL_XOSC32K_WRTLOCK  (1 << 12)
#define OSC32KCTRL_XOSC32K_CGM_SHIFT 13
#define OSC32KCTRL_XOSC32K_CGM_MASK  (0x3 << OSC32KCTRL_XOSC32K_CGM_SHIFT)

/* RTCCTRL register */

#define OSC32KCTRL_RTCCTRL_RTCSEL_SHIFT 0
#define OSC32KCTRL_RTCCTRL_RTCSEL_MASK  (0x7 << OSC32KCTRL_RTCCTRL_RTCSEL_SHIFT)
#  define OSC32KCTRL_RTCCTRL_ULP1K      (0 << OSC32KCTRL_RTCCTRL_RTCSEL_SHIFT)
#  define OSC32KCTRL_RTCCTRL_ULP32K     (1 << OSC32KCTRL_RTCCTRL_RTCSEL_SHIFT)
#  define OSC32KCTRL_RTCCTRL_XOSC1K     (4 << OSC32KCTRL_RTCCTRL_RTCSEL_SHIFT)
#  define OSC32KCTRL_RTCCTRL_XOSC32K    (5 << OSC32KCTRL_RTCCTRL_RTCSEL_SHIFT)

/* STATUS register */

#define OSC32KCTRL_STATUS_XOSC32KRDY (1 << 0)
#define OSC32KCTRL_STATUS_XOSC32KFAIL (1 << 2)

#endif /* __ARCH_ARM_SRC_PIC32CZCA90_HARDWARE_SAM_OSC32KCTRL_H */
