/* SPDX-License-Identifier: Apache-2.0 */
/****************************************************************************
 * arch/arm/src/pic32czca90/sam_config.h
 *
 * PIC32CZ CA90 configuration - determines which SERCOMs are USARTs
 ****************************************************************************/

#ifndef __ARCH_ARM_SRC_PIC32CZCA90_SAM_CONFIG_H
#define __ARCH_ARM_SRC_PIC32CZCA90_SAM_CONFIG_H

#include <nuttx/config.h>

/* How many SERCOMs are configured as USART?
 * PIC32CZCA90_NSERCOM (=10) is defined in arch/arm/include/pic32czca90/chip.h
 */

#define PIC32CZCA90_HAVE_USART0 1
#define PIC32CZCA90_HAVE_USART1 1
#define PIC32CZCA90_HAVE_USART2 1
#define PIC32CZCA90_HAVE_USART3 1
#define PIC32CZCA90_HAVE_USART4 1
#define PIC32CZCA90_HAVE_USART5 1
#define PIC32CZCA90_HAVE_USART6 1
#define PIC32CZCA90_HAVE_USART7 1

#if !defined(CONFIG_PIC32CZCA90_SERCOM0) || \
    !defined(CONFIG_PIC32CZCA90_SERCOM0_ISUSART) || \
    !defined(CONFIG_USART0_SERIALDRIVER)
#  undef PIC32CZCA90_HAVE_USART0
#  undef CONFIG_USART0_SERIAL_CONSOLE
#endif

#if !defined(CONFIG_PIC32CZCA90_SERCOM1) || \
    !defined(CONFIG_PIC32CZCA90_SERCOM1_ISUSART) || \
    !defined(CONFIG_USART1_SERIALDRIVER)
#  undef PIC32CZCA90_HAVE_USART1
#  undef CONFIG_USART1_SERIAL_CONSOLE
#endif

#if !defined(CONFIG_PIC32CZCA90_SERCOM2) || \
    !defined(CONFIG_PIC32CZCA90_SERCOM2_ISUSART) || \
    !defined(CONFIG_USART2_SERIALDRIVER)
#  undef PIC32CZCA90_HAVE_USART2
#  undef CONFIG_USART2_SERIAL_CONSOLE
#endif

#if !defined(CONFIG_PIC32CZCA90_SERCOM3) || \
    !defined(CONFIG_PIC32CZCA90_SERCOM3_ISUSART) || \
    !defined(CONFIG_USART3_SERIALDRIVER)
#  undef PIC32CZCA90_HAVE_USART3
#  undef CONFIG_USART3_SERIAL_CONSOLE
#endif

#if !defined(CONFIG_PIC32CZCA90_SERCOM4) || \
    !defined(CONFIG_PIC32CZCA90_SERCOM4_ISUSART) || \
    !defined(CONFIG_USART4_SERIALDRIVER)
#  undef PIC32CZCA90_HAVE_USART4
#  undef CONFIG_USART4_SERIAL_CONSOLE
#endif

#if !defined(CONFIG_PIC32CZCA90_SERCOM5) || \
    !defined(CONFIG_PIC32CZCA90_SERCOM5_ISUSART) || \
    !defined(CONFIG_USART5_SERIALDRIVER)
#  undef PIC32CZCA90_HAVE_USART5
#  undef CONFIG_USART5_SERIAL_CONSOLE
#endif

#if !defined(CONFIG_PIC32CZCA90_SERCOM6) || \
    !defined(CONFIG_PIC32CZCA90_SERCOM6_ISUSART) || \
    !defined(CONFIG_USART6_SERIALDRIVER)
#  undef PIC32CZCA90_HAVE_USART6
#  undef CONFIG_USART6_SERIAL_CONSOLE
#endif

#if !defined(CONFIG_PIC32CZCA90_SERCOM7) || \
    !defined(CONFIG_PIC32CZCA90_SERCOM7_ISUSART) || \
    !defined(CONFIG_USART7_SERIALDRIVER)
#  undef PIC32CZCA90_HAVE_USART7
#  undef CONFIG_USART7_SERIAL_CONSOLE
#endif

/* Are any USARTs enabled? */

#undef PIC32CZCA90_HAVE_USART
#if defined(PIC32CZCA90_HAVE_USART0) || defined(PIC32CZCA90_HAVE_USART1) || \
    defined(PIC32CZCA90_HAVE_USART2) || defined(PIC32CZCA90_HAVE_USART3) || \
    defined(PIC32CZCA90_HAVE_USART4) || defined(PIC32CZCA90_HAVE_USART5) || \
    defined(PIC32CZCA90_HAVE_USART6) || defined(PIC32CZCA90_HAVE_USART7)
#  define PIC32CZCA90_HAVE_USART 1
#endif

/* Serial console selection */

#if defined(CONFIG_USART0_SERIAL_CONSOLE)
#  undef CONFIG_USART1_SERIAL_CONSOLE
#  undef CONFIG_USART2_SERIAL_CONSOLE
#  undef CONFIG_USART3_SERIAL_CONSOLE
#  undef CONFIG_USART4_SERIAL_CONSOLE
#  undef CONFIG_USART5_SERIAL_CONSOLE
#  undef CONFIG_USART6_SERIAL_CONSOLE
#  undef CONFIG_USART7_SERIAL_CONSOLE
#  define HAVE_SERIAL_CONSOLE 1
#elif defined(CONFIG_USART1_SERIAL_CONSOLE)
#  undef CONFIG_USART0_SERIAL_CONSOLE
#  undef CONFIG_USART2_SERIAL_CONSOLE
#  undef CONFIG_USART3_SERIAL_CONSOLE
#  undef CONFIG_USART4_SERIAL_CONSOLE
#  undef CONFIG_USART5_SERIAL_CONSOLE
#  undef CONFIG_USART6_SERIAL_CONSOLE
#  undef CONFIG_USART7_SERIAL_CONSOLE
#  define HAVE_SERIAL_CONSOLE 1
#elif defined(CONFIG_USART2_SERIAL_CONSOLE)
#  undef CONFIG_USART0_SERIAL_CONSOLE
#  undef CONFIG_USART1_SERIAL_CONSOLE
#  undef CONFIG_USART3_SERIAL_CONSOLE
#  undef CONFIG_USART4_SERIAL_CONSOLE
#  undef CONFIG_USART5_SERIAL_CONSOLE
#  undef CONFIG_USART6_SERIAL_CONSOLE
#  undef CONFIG_USART7_SERIAL_CONSOLE
#  define HAVE_SERIAL_CONSOLE 1
#elif defined(CONFIG_USART3_SERIAL_CONSOLE)
#  undef CONFIG_USART0_SERIAL_CONSOLE
#  undef CONFIG_USART1_SERIAL_CONSOLE
#  undef CONFIG_USART2_SERIAL_CONSOLE
#  undef CONFIG_USART4_SERIAL_CONSOLE
#  undef CONFIG_USART5_SERIAL_CONSOLE
#  undef CONFIG_USART6_SERIAL_CONSOLE
#  undef CONFIG_USART7_SERIAL_CONSOLE
#  define HAVE_SERIAL_CONSOLE 1
#elif defined(CONFIG_USART4_SERIAL_CONSOLE)
#  undef CONFIG_USART0_SERIAL_CONSOLE
#  undef CONFIG_USART1_SERIAL_CONSOLE
#  undef CONFIG_USART2_SERIAL_CONSOLE
#  undef CONFIG_USART3_SERIAL_CONSOLE
#  undef CONFIG_USART5_SERIAL_CONSOLE
#  undef CONFIG_USART6_SERIAL_CONSOLE
#  undef CONFIG_USART7_SERIAL_CONSOLE
#  define HAVE_SERIAL_CONSOLE 1
#elif defined(CONFIG_USART5_SERIAL_CONSOLE)
#  undef CONFIG_USART0_SERIAL_CONSOLE
#  undef CONFIG_USART1_SERIAL_CONSOLE
#  undef CONFIG_USART2_SERIAL_CONSOLE
#  undef CONFIG_USART3_SERIAL_CONSOLE
#  undef CONFIG_USART4_SERIAL_CONSOLE
#  undef CONFIG_USART6_SERIAL_CONSOLE
#  undef CONFIG_USART7_SERIAL_CONSOLE
#  define HAVE_SERIAL_CONSOLE 1
#elif defined(CONFIG_USART6_SERIAL_CONSOLE)
#  undef CONFIG_USART0_SERIAL_CONSOLE
#  undef CONFIG_USART1_SERIAL_CONSOLE
#  undef CONFIG_USART2_SERIAL_CONSOLE
#  undef CONFIG_USART3_SERIAL_CONSOLE
#  undef CONFIG_USART4_SERIAL_CONSOLE
#  undef CONFIG_USART5_SERIAL_CONSOLE
#  undef CONFIG_USART7_SERIAL_CONSOLE
#  define HAVE_SERIAL_CONSOLE 1
#elif defined(CONFIG_USART7_SERIAL_CONSOLE)
#  undef CONFIG_USART0_SERIAL_CONSOLE
#  undef CONFIG_USART1_SERIAL_CONSOLE
#  undef CONFIG_USART2_SERIAL_CONSOLE
#  undef CONFIG_USART3_SERIAL_CONSOLE
#  undef CONFIG_USART4_SERIAL_CONSOLE
#  undef CONFIG_USART5_SERIAL_CONSOLE
#  undef CONFIG_USART6_SERIAL_CONSOLE
#  define HAVE_SERIAL_CONSOLE 1
#else
#  undef HAVE_SERIAL_CONSOLE
#endif

/* SPI configuration */

#define PIC32CZCA90_HAVE_SPI0 1
#define PIC32CZCA90_HAVE_SPI1 1
#define PIC32CZCA90_HAVE_SPI2 1
#define PIC32CZCA90_HAVE_SPI3 1
#define PIC32CZCA90_HAVE_SPI4 1
#define PIC32CZCA90_HAVE_SPI5 1
#define PIC32CZCA90_HAVE_SPI6 1
#define PIC32CZCA90_HAVE_SPI7 1

#if !defined(CONFIG_PIC32CZCA90_SERCOM0) || !defined(CONFIG_PIC32CZCA90_SERCOM0_ISSPI)
#  undef PIC32CZCA90_HAVE_SPI0
#endif
#if !defined(CONFIG_PIC32CZCA90_SERCOM1) || !defined(CONFIG_PIC32CZCA90_SERCOM1_ISSPI)
#  undef PIC32CZCA90_HAVE_SPI1
#endif
#if !defined(CONFIG_PIC32CZCA90_SERCOM2) || !defined(CONFIG_PIC32CZCA90_SERCOM2_ISSPI)
#  undef PIC32CZCA90_HAVE_SPI2
#endif
#if !defined(CONFIG_PIC32CZCA90_SERCOM3) || !defined(CONFIG_PIC32CZCA90_SERCOM3_ISSPI)
#  undef PIC32CZCA90_HAVE_SPI3
#endif
#if !defined(CONFIG_PIC32CZCA90_SERCOM4) || !defined(CONFIG_PIC32CZCA90_SERCOM4_ISSPI)
#  undef PIC32CZCA90_HAVE_SPI4
#endif
#if !defined(CONFIG_PIC32CZCA90_SERCOM5) || !defined(CONFIG_PIC32CZCA90_SERCOM5_ISSPI)
#  undef PIC32CZCA90_HAVE_SPI5
#endif
#if !defined(CONFIG_PIC32CZCA90_SERCOM6) || !defined(CONFIG_PIC32CZCA90_SERCOM6_ISSPI)
#  undef PIC32CZCA90_HAVE_SPI6
#endif
#if !defined(CONFIG_PIC32CZCA90_SERCOM7) || !defined(CONFIG_PIC32CZCA90_SERCOM7_ISSPI)
#  undef PIC32CZCA90_HAVE_SPI7
#endif

#undef PIC32CZCA90_HAVE_SPI
#if defined(PIC32CZCA90_HAVE_SPI0) || defined(PIC32CZCA90_HAVE_SPI1) || \
    defined(PIC32CZCA90_HAVE_SPI2) || defined(PIC32CZCA90_HAVE_SPI3) || \
    defined(PIC32CZCA90_HAVE_SPI4) || defined(PIC32CZCA90_HAVE_SPI5) || \
    defined(PIC32CZCA90_HAVE_SPI6) || defined(PIC32CZCA90_HAVE_SPI7)
#  define PIC32CZCA90_HAVE_SPI 1
#endif

/* I2C configuration */

#define PIC32CZCA90_HAVE_I2C0_MASTER 1
#define PIC32CZCA90_HAVE_I2C1_MASTER 1
#define PIC32CZCA90_HAVE_I2C2_MASTER 1
#define PIC32CZCA90_HAVE_I2C3_MASTER 1
#define PIC32CZCA90_HAVE_I2C4_MASTER 1
#define PIC32CZCA90_HAVE_I2C5_MASTER 1
#define PIC32CZCA90_HAVE_I2C6_MASTER 1
#define PIC32CZCA90_HAVE_I2C7_MASTER 1

#if !defined(CONFIG_PIC32CZCA90_SERCOM0) || !defined(CONFIG_PIC32CZCA90_SERCOM0_ISI2C)
#  undef PIC32CZCA90_HAVE_I2C0_MASTER
#endif
#if !defined(CONFIG_PIC32CZCA90_SERCOM1) || !defined(CONFIG_PIC32CZCA90_SERCOM1_ISI2C)
#  undef PIC32CZCA90_HAVE_I2C1_MASTER
#endif
#if !defined(CONFIG_PIC32CZCA90_SERCOM2) || !defined(CONFIG_PIC32CZCA90_SERCOM2_ISI2C)
#  undef PIC32CZCA90_HAVE_I2C2_MASTER
#endif
#if !defined(CONFIG_PIC32CZCA90_SERCOM3) || !defined(CONFIG_PIC32CZCA90_SERCOM3_ISI2C)
#  undef PIC32CZCA90_HAVE_I2C3_MASTER
#endif
#if !defined(CONFIG_PIC32CZCA90_SERCOM4) || !defined(CONFIG_PIC32CZCA90_SERCOM4_ISI2C)
#  undef PIC32CZCA90_HAVE_I2C4_MASTER
#endif
#if !defined(CONFIG_PIC32CZCA90_SERCOM5) || !defined(CONFIG_PIC32CZCA90_SERCOM5_ISI2C)
#  undef PIC32CZCA90_HAVE_I2C5_MASTER
#endif
#if !defined(CONFIG_PIC32CZCA90_SERCOM6) || !defined(CONFIG_PIC32CZCA90_SERCOM6_ISI2C)
#  undef PIC32CZCA90_HAVE_I2C6_MASTER
#endif
#if !defined(CONFIG_PIC32CZCA90_SERCOM7) || !defined(CONFIG_PIC32CZCA90_SERCOM7_ISI2C)
#  undef PIC32CZCA90_HAVE_I2C7_MASTER
#endif

#undef PIC32CZCA90_HAVE_I2C_MASTER
#if defined(PIC32CZCA90_HAVE_I2C0_MASTER) || \
    defined(PIC32CZCA90_HAVE_I2C1_MASTER) || \
    defined(PIC32CZCA90_HAVE_I2C2_MASTER) || \
    defined(PIC32CZCA90_HAVE_I2C3_MASTER) || \
    defined(PIC32CZCA90_HAVE_I2C4_MASTER) || \
    defined(PIC32CZCA90_HAVE_I2C5_MASTER) || \
    defined(PIC32CZCA90_HAVE_I2C6_MASTER) || \
    defined(PIC32CZCA90_HAVE_I2C7_MASTER)
#  define PIC32CZCA90_HAVE_I2C_MASTER 1
#endif

#endif /* __ARCH_ARM_SRC_PIC32CZCA90_SAM_CONFIG_H */
